name: CI Pipeline

on:
  pull_request:
     branches:
       - main

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
       - name: checkout code
         used: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.9'

       - name: Insttall dependencies
         run:
           python -m venv env
           source env/bin/activate
           pip install -r requirements.txt

       - name: Run tests
         run: |
           source env/bin/activate
          pytest 
